name = "based_sqlite"
version = "1.0.0"
description = "A sqlite adapter for based"
gleam = "~> 1.0"

licences = ["Apache-2.0"]
repository = { type = "github", user = "stndrs", repo = "based_sqlite" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
sqlight = "~> 0.9"
based = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
